
ads-admob:
- packages/expo-ads-admob/**/*
ads-facebook:
- packages/expo-ads-facebook/**/*
analytics-amplitude:
- packages/expo-analytics-amplitude/**/*
analytics-segment:
- packages/expo-analytics-segment/**/*
app-auth:
- packages/expo-app-auth/**/*
app-loader-provider:
- packages/expo-app-loader-provider/**/*
apple-authentication:
- packages/expo-apple-authentication/**/*
application:
- packages/expo-application/**/*
asset:
- packages/expo-asset/**/*
av:
- packages/expo-av/**/*
background-fetch:
- packages/expo-background-fetch/**/*
barcode-scanner:
- packages/expo-barcode-scanner/**/*
battery:
- packages/expo-battery/**/*
bluetooth:
- packages/expo-bluetooth/**/*
blur:
- packages/expo-blur/**/*
branch:
- packages/expo-branch/**/*
brightness:
- packages/expo-brightness/**/*
calendar:
- packages/expo-calendar/**/*
camera:
- packages/expo-camera/**/*
cellular:
- packages/expo-cellular/**/*
constants:
- packages/expo-constants/**/*
contacts:
- packages/expo-contacts/**/*
crypto:
- packages/expo-crypto/**/*
device:
- packages/expo-device/**/*
document-picker:
- packages/expo-document-picker/**/*
face-detector:
- packages/expo-face-detector/**/*
facebook:
- packages/expo-facebook/**/*
file-system:
- packages/expo-file-system/**/*
font:
- packages/expo-font/**/*
gl-cpp:
- packages/expo-gl-cpp/**/*
gl:
- packages/expo-gl/**/*
google-app-auth:
- packages/expo-google-app-auth/**/*
google-sign-in:
- packages/expo-google-sign-in/**/*
haptics:
- packages/expo-haptics/**/*
image-manipulator:
- packages/expo-image-manipulator/**/*
image-picker:
- packages/expo-image-picker/**/*
in-app-purchases:
- packages/expo-in-app-purchases/**/*
intent-launcher:
- packages/expo-intent-launcher/**/*
keep-awake:
- packages/expo-keep-awake/**/*
linear-gradient:
- packages/expo-linear-gradient/**/*
local-authentication:
- packages/expo-local-authentication/**/*
localization:
- packages/expo-localization/**/*
location:
- packages/expo-location/**/*
mail-composer:
- packages/expo-mail-composer/**/*
media-library:
- packages/expo-media-library/**/*
module-scripts:
- packages/expo-module-scripts/**/*
module-template:
- packages/expo-module-template/**/*
network:
- packages/expo-network/**/*
payments-stripe:
- packages/expo-payments-stripe/**/*
permissions:
- packages/expo-permissions/**/*
print:
- packages/expo-print/**/*
processing:
- packages/expo-processing/**/*
random:
- packages/expo-random/**/*
secure-store:
- packages/expo-secure-store/**/*
sensors:
- packages/expo-sensors/**/*
sharing:
- packages/expo-sharing/**/*
sms:
- packages/expo-sms/**/*
speech:
- packages/expo-speech/**/*
sqlite:
- packages/expo-sqlite/**/*
store-review:
- packages/expo-store-review/**/*
task-manager:
- packages/expo-task-manager/**/*
updates:
- packages/expo-updates/**/*
video-thumbnails:
- packages/expo-video-thumbnails/**/*
web-browser:
- packages/expo-web-browser/**/*
yarn-workspaces:
- packages/expo-yarn-workspaces/**/*
expo:
- packages/expo/**/*
