name: docs

defaults:
  run:
    working-directory: docs

on:
  push:
    branches: [ '@nick/github-previous-status' ]
    paths:
      - 'docs/**'
      - '.github/workflows/docs.yml'

jobs:
  danger:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/github-script@v1
        id: previous-status
        with:
          result-encoding: string
          script: |
            const checks = await github.checks.listForRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: 'master',
              filter: 'latest',
              status: 'completed'
            });
            console.info(JSON.stringify(checks, null, 4));

            const last = checks.data.check_runs[0]

            if (last) {
              return last.conclusion
            }
      - run: exit 1
      - name: Check out repository
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - uses: actions/cache@v1
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('docs/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - run: yarn install --frozen-lockfile
      - run: yarn danger ci
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/github-script@v1
        id: previous-status
        with:
          result-encoding: string
          script: |
            const checks = await github.checks.listForRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: context.ref.replace('refs/heads/', ''),
              check_name: '${{ github.job }}',
              status: 'completed'
            });
            console.info(JSON.stringify(checks, null, 4));

            const last = checks.data.check_runs[0]

            if (last) {
              return last.conclusion
            }
      - run: exit 1
      - name: Check out repository
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - uses: actions/cache@v1
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('docs/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - run: yarn install --frozen-lockfile
      - run: yarn export
        timeout-minutes: 15
      - name: test links
        run: |
          yarn export-server &
          while ! nc -z localhost 8000; do
            sleep 1
          done
          yarn test-links http://127.0.0.1:8000
        timeout-minutes: 1
      - run: sudo apt-get install awscli
      - run: ./deploy.sh
        if: ${{ github.event.ref == 'refs/heads/master' }}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - uses: 8398a7/action-slack@v3
        if: github.event.ref == 'refs/heads/master' && (failure() || (steps.previous-status.outputs.result == 'failure'))
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SLACK_WEBHOOK_URL: ${{ secrets.slack_webhook_docs }}
        with:
          channel: '#docs'
          status: ${{ job.status }}
          fields: commit,author,action,message
          author_name: docs build
